import type { CredentialItem } from "@/lib/types";

export const CREDENTIALS: CredentialItem[] = [
  {
    id: "ibm-agentic-ai",
    title: "IBM Agentic AI Specialisation",
    issuer: "IBM",
    category: "Agentic AI & RAG",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: true,
    tags: ["Agentic AI", "IBM"],
  },
  {
    id: "langchain-cert",
    title: "LangChain",
    issuer: "LangChain / DeepLearning.AI",
    category: "Agentic AI & RAG",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: true,
    tags: ["LangChain", "Agentic AI"],
  },
  {
    id: "langgraph-cert",
    title: "LangGraph",
    issuer: "LangChain / DeepLearning.AI",
    category: "Agentic AI & RAG",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: true,
    tags: ["LangGraph", "Agentic AI"],
  },
  {
    id: "crewai-cert",
    title: "CrewAI",
    issuer: "CrewAI / DeepLearning.AI",
    category: "Agentic AI & RAG",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: false,
    tags: ["CrewAI", "Agentic AI"],
  },
  {
    id: "autogen-cert",
    title: "AutoGen",
    issuer: "Microsoft / DeepLearning.AI",
    category: "Agentic AI & RAG",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: false,
    tags: ["AutoGen", "Multi-Agent"],
  },
  {
    id: "advanced-rag",
    title: "Advanced RAG",
    issuer: "DeepLearning.AI",
    category: "Agentic AI & RAG",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: true,
    tags: ["RAG", "Retrieval"],
  },
  {
    id: "deeplearning-spec",
    title: "Deep Learning Specialisation",
    issuer: "DeepLearning.AI / Coursera",
    category: "Deep Learning",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: true,
    tags: ["Deep Learning", "Neural Networks", "CNNs"],
  },
  {
    id: "building-agentic-rag-llamaindex",
    title: "Building Agentic RAG with LlamaIndex",
    issuer: "DeepLearning.AI",
    category: "Generative AI Systems",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: true,
    tags: ["RAG", "LlamaIndex", "Agentic AI"],
  },
  {
    id: "multimodal-llama",
    title: "Multimodal Llama",
    issuer: "DeepLearning.AI",
    category: "Generative AI Systems",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: false,
    tags: ["Multimodal AI", "LLaMA"],
  },
  {
    id: "transformers-cv",
    title: "Transformers for Computer Vision",
    issuer: "Hugging Face / DeepLearning.AI",
    category: "Computer Vision",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: false,
    tags: ["Computer Vision", "Transformers"],
  },
  {
    id: "kaggle-pandas",
    title: "Pandas",
    issuer: "Kaggle",
    category: "Data",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: false,
    tags: ["Python", "Data", "Pandas"],
  },
  {
    id: "python-cert",
    title: "Python",
    issuer: "Various",
    category: "Programming",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: false,
    tags: ["Python", "Programming"],
  },
];

export const CREDENTIAL_CATEGORIES = [
  "All",
  "Agentic AI & RAG",
  "Generative AI Systems",
  "Deep Learning",
  "Computer Vision",
  "Data",
  "Programming",
  "Innovation & Entrepreneurship",
];
