import type { CredentialItem } from "@/lib/types";

export const CREDENTIALS: CredentialItem[] = [
  {
    id: "ibm-agentic-ai",
    title: "Building AI Agents and  Agentic AI Workflows Specialisation",
    issuer: "IBM",
    category: "Agentic AI & RAG",
    credentialId: "JYVU7YZIN3XW",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Agentic AI", "IBM"],
  },
  {
    id: "ibm-vector-dbs",
    title: "Vector Databases for RAG: An Introduction",
    issuer: "IBM",
    category: "Agentic AI & RAG",
    credentialId: "JOM77NSV65ZB",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["IBM","RAG", "Vector Databases"],
  },
  {
    id: "ibm-advanced-vector-dbs",
    title: "Advanced RAG with Vector Databases and Retrievers",
    issuer: "IBM",
    category: "Agentic AI & RAG",
    credentialId: "96M2T7RXNQ7B",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["IBM","RAG", "Vector Databases"],
  },
  {
    id: "langchain-crewai-cert",
    title: "Agentic AI with LangGraph, CrewAI, AutoGen and BeeAI",
    issuer: "IBM",
    category: "Agentic AI & RAG",
    credentialId: "G2WW138WTDA8",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["LangGraph", "Agentic AI","BeeAI"],
  },
  {
    id: "langgraph-langchain-cert",
    title: "Agentic AI with LangChain and LangGraph",
    issuer: "IBM",
    category: "Agentic AI & RAG",
    credentialId: "ZYLAO5B1DIJX",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["LangGraph", "Agentic AI","Langchain"],
  },
  {
    id: "ai-agents-fundamentals-cert",
    title: "Fundamentals of Building AI Agents",
    issuer: "CrewAI / DeepLearning.AI",
    category: "Agentic AI & RAG",
    credentialId: "8LD80HX22ZZV",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: false,
    tags: ["AI", "Agentic AI","LLMs"],
  },
  {
    id: "model-context-protocol-cert",
    title: "Introduction to Model Context Protocol",
    issuer: "Anthropic",
    category: "Agentic AI & RAG",
    credentialId: "CADTJHILZR59",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: false,
    tags: ["Claude", "MCP", "Agentic AI"],
  },
  {
    id: "model-context-protocol-advanced-cert",
    title: "Model Context Protocol: Advanced Topics",
    issuer: "Anthropic",
    category: "Agentic AI & RAG",
    credentialId: "HDNTCVVIFSLO",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Claude", "MCP", "Agentic AI"],
  },
  {
    id: "deeplearning-spec",
    title: "Deep Learning Specialisation",
    issuer: "DeepLearning.AI / Coursera",
    category: "Deep Learning",
    credentialId: "needs-review",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Deep Learning", "Neural Networks", "CNNs"],
  },
  {
    id: "building-agentic-rag-llamaindex",
    title: "Building Agentic RAG with LlamaIndex",
    issuer: "DeepLearning.AI",
    category: "Generative AI Systems",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: true,
    tags: ["RAG", "LlamaIndex", "Agentic AI"],
  },
  {
    id: "multimodal-llama",
    title: "Multimodal Llama",
    issuer: "DeepLearning.AI",
    category: "Generative AI Systems",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: false,
    tags: ["Multimodal AI", "LLaMA"],
  },
  {
    id: "transformers-cv",
    title: "Transformers for Computer Vision",
    issuer: "Hugging Face / DeepLearning.AI",
    category: "Computer Vision",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: false,
    tags: ["Computer Vision", "Transformers"],
  },
  {
    id: "kaggle-pandas",
    title: "Pandas",
    issuer: "Kaggle",
    category: "Data",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: false,
    tags: ["Python", "Data", "Pandas"],
  },
  {
    id: "python-cert",
    title: "Python",
    issuer: "Various",
    category: "Programming",
    credentialId: "needs-review",
    verifyUrl: "needs-review",
    verificationStatus: "needs-review",
    featured: false,
    tags: ["Python", "Programming"],
  },
];

export const CREDENTIAL_CATEGORIES = [
  "All",
  "Agentic AI & RAG",
  "Generative AI Systems",
  "Deep Learning",
  "Computer Vision",
  "Data",
  "Programming",
  "Innovation & Entrepreneurship",
];
