import type { CredentialItem } from "@/lib/types";

export const CREDENTIALS: CredentialItem[] = [
  {
    id: "ibm-agentic-ai",
    title: "Building AI Agents and  Agentic AI Workflows Specialisation",
    issuer: "IBM",
    category: "Agentic AI & RAG",
    credentialId: "JYVU7YZIN3XW",
    verifyUrl: "https://www.coursera.org/account/accomplishments/specialization/JYVU7YZIN3XW",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Agentic AI", "IBM"],
  },
  {
    id: "ibm-vector-dbs",
    title: "Vector Databases for RAG: An Introduction",
    issuer: "IBM",
    category: "Agentic AI & RAG",
    credentialId: "JOM77NSV65ZB",
    verifyUrl: "https://www.coursera.org/account/accomplishments/verify/JOM77NSV65ZB",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["IBM","RAG", "Vector Databases"],
  },
  {
    id: "ibm-advanced-vector-dbs",
    title: "Advanced RAG with Vector Databases and Retrievers",
    issuer: "IBM",
    category: "Agentic AI & RAG",
    credentialId: "96M2T7RXNQ7B",
    verifyUrl: "https://www.coursera.org/account/accomplishments/verify/96M2T7RXNQ7B",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["IBM","RAG", "Vector Databases"],
  },
  {
    id: "langchain-crewai-cert",
    title: "Agentic AI with LangGraph, CrewAI, AutoGen and BeeAI",
    issuer: "IBM",
    category: "Agentic AI & RAG",
    credentialId: "G2WW138WTDA8",
    verifyUrl: "https://www.coursera.org/account/accomplishments/verify/G2WW138WTDA8",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["LangGraph", "Agentic AI","BeeAI"],
  },
  {
    id: "langgraph-langchain-cert",
    title: "Agentic AI with LangChain and LangGraph",
    issuer: "IBM",
    category: "Agentic AI & RAG",
    credentialId: "ZYLAO5B1DIJX",
    verifyUrl: "https://www.coursera.org/account/accomplishments/verify/ZYLAO5B1DIJX",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["LangGraph", "Agentic AI","Langchain"],
  },
  {
    id: "ai-agents-fundamentals-cert",
    title: "Fundamentals of Building AI Agents",
    issuer: "IBM",
    category: "Agentic AI & RAG",
    credentialId: "8LD80HX22ZZV",
    verifyUrl: "https://www.coursera.org/account/accomplishments/verify/8LD80HX22ZZV",
    verificationStatus: "verified-public",
    featured: false,
    tags: ["AI", "Agentic AI","LLMs"],
  },
  {
    id: "model-context-protocol-cert",
    title: "Introduction to Model Context Protocol",
    issuer: "Anthropic",
    category: "Agentic AI & RAG",
    credentialId: "CADTJHILZR59",
    verifyUrl: "https://www.coursera.org/account/accomplishments/verify/CADTJHILZR59",
    verificationStatus: "verified-public",
    featured: false,
    tags: ["Claude", "MCP", "Agentic AI"],
  },
  {
    id: "model-context-protocol-advanced-cert",
    title: "Model Context Protocol: Advanced Topics",
    issuer: "Anthropic",
    category: "Agentic AI & RAG",
    credentialId: "HDNTCVVIFSLO",
    verifyUrl: "https://www.coursera.org/account/accomplishments/verify/HDNTCVVIFSLO",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Claude", "MCP", "Agentic AI"],
  },
  {
    id: "neural-networks-and-deep-learning",
    title: "Neural Networks and Deep Learning",
    issuer: "DeepLearning.AI / Coursera",
    category: "Deep Learning",
    credentialId: "LWLCERL3FM2Y",
    verifyUrl: "https://www.coursera.org/account/accomplishments/verify/LWLCERL3FM2Y",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Deep Learning", "Neural Networks", "Pytorch"],
  },
  {
    id: "structuring-machine-learning-projects",
    title: "Structuring Machine Learning Projects",
    issuer: "DeepLearning.AI / Coursera",
    category: "Deep Learning",
    credentialId: "SG56PYM7SG7H",
    verifyUrl: "https://www.coursera.org/account/accomplishments/verify/SG56PYM7SG7H",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Deep Learning", "Neural Networks", "Pytorch"],
  },
  {
    id: "convolutional-neural-networks",
    title: "Convolutional Neural Networks",
    issuer: "DeepLearning.AI / Coursera",
    category: "Deep Learning",
    credentialId: "DXM4JTEFYACS",
    verifyUrl: "https://www.coursera.org/account/accomplishments/verify/DXM4JTEFYACS",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Deep Learning", "Convolutional Neural Networks", "Pytorch"],
  },
  {
    id: "sequence-models",
    title: "Sequence Models",
    issuer: "DeepLearning.AI / Coursera",
    category: "Deep Learning",
    credentialId: "474VBZNGYP3U",
    verifyUrl: "https://www.coursera.org/account/accomplishments/verify/474VBZNGYP3U",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Deep Learning", "Natural Language Processing", "Pytorch"],
  },
  {
    id: "improving-deep-neural-networks",
    title: "Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization",
    issuer: "DeepLearning.AI / Coursera",
    category: "Deep Learning",
    credentialId: "79DC8YJGV3SL",
    verifyUrl: "https://www.coursera.org/account/accomplishments/verify/79DC8YJGV3SL",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Deep Learning", "Neural Networks", "Python"],
  },
  {
    id: "building-agentic-rag-llamaindex",
    title: "Building Agentic RAG with LlamaIndex",
    issuer: "DeepLearning.AI",
    category: "Generative AI Systems",
    credentialId: "",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["RAG", "LlamaIndex", "Agentic AI"],
  },
  {
    id: "multimodal-llama",
    title: "Multimodal Llama",
    issuer: "DeepLearning.AI",
    category: "Generative AI Systems",
    credentialId: "",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: false,
    tags: ["Multimodal AI", "LLaMA"],
  },
  {
    id: "generative-adversarial-networks",
    title: "Introduction to Generative Adversarial Networks (GANs)",
    issuer: "Linkedin Learning",
    category: "Generative AI Systems",
    credentialId: "63eece46e615f987d22c770aef15c43e7480aa1a1ac2b1b3afa52636bb44631b",
    verifyUrl: "https://www.linkedin.com/learning/certificates/63eece46e615f987d22c770aef15c43e7480aa1a1ac2b1b3afa52636bb44631b",
    verificationStatus: "verified-public",
    featured: false,
    tags: ["Generative AI", "Pytorch", "GANs"],
  },
  {
    id: "transformers-cv",
    title: "Advanced AI: Transformers for Computer Vision",
    issuer: "Linkedin Learning",
    category: "Computer Vision",
    credentialId: "574b2f5363fc4ac3f172901508a6c2d2965904d7acb9aa6e19ac5e84fb35c20f",
    verifyUrl: "https://www.linkedin.com/learning/certificates/574b2f5363fc4ac3f172901508a6c2d2965904d7acb9aa6e19ac5e84fb35c20f",
    verificationStatus: "verified-public",
    featured: false,
    tags: ["Computer Vision", "Transformers","Pytorch"],
  },
  {
    id: "tum-startup-launchpad",
    title: "Startup Launchpad",
    issuer: "UnternehmerTUM",
    category: "Innovation & Entrepreneurship",
    credentialId: "",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Leadership", "Business Development", "Entrepreneurship"],
  },
  {
    id: "cyber-valley-incubator",
    title: "Cyber Valley AI Incubator",
    issuer: "Cyber Valley",
    category: "Innovation & Entrepreneurship",
    credentialId: "",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Artificial Intelligence", "Business Development", "Entrepreneurship"],
  },
  {
    id: "cie-basecamp",
    title: "Center for Innovation and Entrepreneurship Basecamp",
    issuer: "PES University",
    category: "Innovation & Entrepreneurship",
    credentialId: "",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Leadership", "Business Development", "Entrepreneurship"],
  },
  {
    id: "startup-ideation",
    title: "PES University Entrepreneurship Cell Startup Ideation",
    issuer: "PES University",
    category: "Innovation & Entrepreneurship",
    credentialId: "",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Startups", "Business Development", "Entrepreneurship"],
  },
{
    id: "serverless-applications",
    title: "Serverless Applications",
    issuer: "Microsoft",
    category: "Programming",
    credentialId: "Z7HNCUB2I6YZ",
    verifyUrl: "https://www.coursera.org/account/accomplishments/verify/Z7HNCUB2I6YZ",
    verificationStatus: "verified-public",
    featured: true,
    tags: ["Serverless", "Backend", "Microsoft Azure"],
  },

  {
    id: "kaggle-pandas",
    title: "Pandas",
    issuer: "Kaggle",
    category: "Data",
    credentialId: "",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: false,
    tags: ["Python", "Data", "Pandas"],
  },
  {
    id: "kaggle-data-visualization",
    title: "Data Visualization",
    issuer: "Kaggle",
    category: "Data",
    credentialId: "",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: false,
    tags: ["Python", "Seaborn", "Matlotlib"],
  },
  {
    id: "java-cert",
    title: "Java",
    issuer: "Sololearn",
    category: "Programming",
    credentialId: "",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: false,
    tags: ["Java", "Programming","OOP"],
  },
  {
    id: "python-cert",
    title: "Python",
    issuer: "Sololearn",
    category: "Programming",
    credentialId: "",
    verifyUrl: "",
    verificationStatus: "verified-public",
    featured: false,
    tags: ["Python", "Programming","OOP"],
  },
];

export const CREDENTIAL_CATEGORIES = [
  "All",
  "Agentic AI & RAG",
  "Generative AI Systems",
  "Deep Learning",
  "Computer Vision",
  "Data",
  "Programming",
  "Innovation & Entrepreneurship",
];
