import type { ExperienceItem } from "@/lib/types";

export const EXPERIENCE: ExperienceItem[] = [
  {
    id: "hilti",
    title: "Hilti",
    subtitle: "Working Student Agentic AI",
    summary:
      "Working on Agentic AI-related initiatives in an industrial context, combining agentic AI, data, workflow thinking,embedded systems knowledge and practical business use cases.",
    organization: "Hilti",
    role: "Working Student Agentic AI Engineer",
    track: "engineering",
    startDate: "May 2026",
    endDate: "present",
    featured: true,
    verificationStatus: "verified-public",
    visibility: "public",
    tags: ["Industrial AI", "Applied AI", "Workflow Automation","Agentic AI"],
  },
  {
    id: "bosch-ebike",
    title: "Bosch eBike Systems",
    subtitle: "Applied Machine Learning and Data Science",
    summary:
      "Applied Machine Learning and data science work covering master's thesis, acoustic and vibration data analysis, explainable machine learning, developing custom tools for NVH engineers  and industrial-scale data pipeline development.",
    organization: "Bosch eBike Systems",
    role: "Data Scientist",
    track: "engineering",
    startDate: "June 2023",
    endDate: "March 2025",
    featured: true,
    verificationStatus: "verified-public",
    visibility: "public",
    tags: ["Applied ML", "Explainable AI", "Industrial ML", "ETL Pipelines", "Signal Processing","Deep Learning","Audio Analysis"],
  },
  {
    id: "forwiss",
    title: "FORWISS - University of Passau",
    subtitle: "Research Assistant",
    summary:
      "Signal and data-processing research covering NetCDF and HDF5 formats, compression of wavelet-based signals, research software development, and publication contribution.",
    organization: "FORWISS, University of Passau",
    role: "Research Assistant",
    track: "research",
    startDate: "June 2022",
    endDate: "July 2023",
    featured: true,
    verificationStatus: "verified-public",
    visibility: "public",
    tags: ["Research", "Signal Processing", "Wavelets", "Research Software","Data Compression","Chunking Algorithms"],
  },
  {
    id: "startup-ecosystem",
    title: "Startup Ecosystem",
    subtitle: "Founder, Builder, Hackathon Participant",
    summary:
      "Active participation in Cyber Valley AI Incubator, UnternehmerTUM Startup Launchpad, hackathons, makeathons, and AI builder programmes.",
    organization: "Cellvara/Zestlearn",
    role: "Founder / Builder",
    track: "entrepreneurship",
    startDate: "May 2025",
    endDate: "present",
    featured: true,
    verificationStatus: "verified-public",
    visibility: "public",
    tags: ["Startup", "AI Incubator", "Venture Building"],
  },
  {
    id: "snowball-effect",
    title: "Strategy Consultant – Impact Measurement & Scaling",
    subtitle: "Co-op / Project-based",
    summary:
      "Led a three-person consulting project for Snowball Effect, working with two teammates to improve the organization's impact measurement, KPI, and scaling strategy frameworks, including analysis of survey data, KPI structures, impact reports, and internal assessment processes, and developing recommendations for a clearer theory of change and a more transparent assessment framework for new and existing solutions.",
    organization: "Snowball Effect",
    role: "Strategy Consultant",
    track: "entrepreneurship",
    startDate: "March 2026",
    endDate: "July 2026",
    featured: true,
    verificationStatus: "verified-public",
    visibility: "public",
    tags: ["Leadership", "Strategy Consulting", "Impact Measurement", "KPI Development", "Theory of Change", "Social Innovation"],
  },
];
