import type { ExperienceItem } from "@/lib/types";

export const EXPERIENCE: ExperienceItem[] = [
  {
    id: "hilti",
    title: "Hilti",
    subtitle: "Working Student AI",
    summary:
      "Working on AI-related initiatives in an industrial context, combining applied AI, data, workflow thinking, and practical business use cases.",
    organization: "Hilti",
    role: "Working Student AI",
    track: "engineering",
    startDate: "May 2026",
    endDate: "present",
    featured: true,
    verificationStatus: "verified-public",
    visibility: "public",
    tags: ["Industrial AI", "Applied AI", "Workflow Automation","Agentic AI"],
  },
  {
    id: "bosch-ebike",
    title: "Bosch eBike Systems",
    subtitle: "Applied ML and Data Science",
    summary:
      "Applied ML and data science work covering master's thesis, acoustic and vibration data analysis, explainable machine learning, and industrial-scale data pipeline development.",
    organization: "Bosch eBike Systems",
    role: "needs-review",
    track: "engineering",
    startDate: "June 2023",
    endDate: "March 2025",
    featured: true,
    verificationStatus: "verified-public",
    visibility: "public",
    tags: ["Applied ML", "Explainable AI", "Industrial ML", "ETL Pipelines", "Signal Processing","Deep Learning","Audio Analysis"],
  },
  {
    id: "forwiss",
    title: "FORWISS — University of Passau",
    subtitle: "Research Assistant",
    summary:
      "Signal and data-processing research covering NetCDF and HDF5 formats, compression of wavelet-based signals, research software development, and publication contribution.",
    organization: "FORWISS, University of Passau",
    role: "Research Assistant",
    track: "research",
    startDate: "June 2022",
    endDate: "July 2023",
    featured: true,
    verificationStatus: "verified-public",
    visibility: "public",
    tags: ["Research", "Signal Processing", "Wavelets", "Research Software","Data Compression","Chunking Algorithms"],
  },
  {
    id: "startup-ecosystem",
    title: "Startup Ecosystem",
    subtitle: "Founder, Builder, Hackathon Participant",
    summary:
      "Active participation in Cyber Valley AI Incubator, UnternehmerTUM Startup Launchpad, hackathons, makeathons, and AI builder programmes.",
    organization: "Cellvara/Zestlearn",
    role: "Founder / Builder",
    track: "entrepreneurship",
    featured: true,
    verificationStatus: "verified-public",
    visibility: "public",
    tags: ["Startup", "AI Incubator", "Venture Building"],
  },
];
