import type { ProjectItem } from "@/lib/types";

export const FEATURED_PROJECTS: ProjectItem[] = [
  {
    id: "docchat",
    title: "DocChat",
    summary: "Verified multi-agent RAG for reliable document intelligence.",
    description:
      "A document Q&A system using retrieval, reasoning, and verification agents to provide more reliable answers over uploaded documents. Implements hybrid BM25 and vector retrieval with scope detection and fact verification.",
    bestAngle: "Reliable RAG and verification architecture",
    featured: true,
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    githubUrl: "https://github.com/PRONGS-CHIRAG/Docchat",
    tags: ["RAG", "LangChain", "Vector DB", "Verification", "Document AI", "Multi-Agent"],
    category: "Agentic AI & RAG",
    architectureNodes: [
      {
        id: "doc-upload",
        label: "Document Upload",
        responsibility: "Accept and parse uploaded documents",
        input: "PDF / text files",
        output: "Raw text chunks",
        technology: "LangChain document loaders",
        failureMode: "Malformed or scanned PDFs",
        validationMethod: "File type validation + extraction fallback",
      },
      {
        id: "doc-chunking",
        label: "Chunking",
        responsibility: "Split text into retrieval-ready segments",
        input: "Raw text",
        output: "Overlapping text chunks",
        technology: "RecursiveCharacterTextSplitter",
        failureMode: "Chunk boundary cuts semantic units",
        validationMethod: "Chunk size + overlap tuning",
      },
      {
        id: "doc-embedding",
        label: "Embedding",
        responsibility: "Generate vector representations",
        input: "Text chunks",
        output: "Dense vectors",
        technology: "Embedding model + ChromaDB",
        failureMode: "Embedding model latency",
        validationMethod: "Cosine similarity spot check",
      },
      {
        id: "doc-hybrid-retrieval",
        label: "Hybrid Retrieval",
        responsibility: "BM25 sparse + dense vector retrieval fusion",
        input: "User query",
        output: "Top-k relevant chunks",
        technology: "BM25 + ChromaDB",
        failureMode: "Out-of-scope queries",
        validationMethod: "Scope detection pre-check",
      },
      {
        id: "doc-research-agent",
        label: "Research Agent",
        responsibility: "Reason over retrieved context",
        input: "Chunks + query",
        output: "Draft answer",
        technology: "LangChain agent + LLM",
        failureMode: "Hallucination on sparse context",
        validationMethod: "Source grounding check",
      },
      {
        id: "doc-verification-agent",
        label: "Verification Agent",
        responsibility: "Validate answer against source chunks",
        input: "Draft answer + chunks",
        output: "Verified or corrected answer",
        technology: "LangChain agent",
        failureMode: "Verification disagreement loop",
        validationMethod: "Self-correction iteration cap",
      },
    ],
  },
  {
    id: "prepai",
    title: "PrepAI",
    summary:
      "AI interview-preparation platform that converts a résumé and job description into a personalised mock interview and coach-style report.",
    description:
      "PrepAI extracts candidate and job information, identifies gaps, generates interview questions, evaluates answers, and produces a final coaching report. Optional voice interaction via Whisper and ElevenLabs.",
    bestAngle: "Orchestration, structured outputs, APIs, schemas, and evaluation",
    featured: true,
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    githubUrl: "https://github.com/PRONGS-CHIRAG/InterviewPrep",
    tags: ["LangGraph", "FastAPI", "Gradio", "LangChain", "Whisper", "ElevenLabs", "Pydantic"],
    category: "Agentic AI & RAG",
    architectureNodes: [
      {
        id: "prep-input",
        label: "Resume + Job Description",
        responsibility: "Intake and parse candidate materials",
        input: "PDF resume + job description text",
        output: "Structured candidate profile",
        technology: "FastAPI + PDF extraction",
        failureMode: "Unstructured PDF parsing errors",
        validationMethod: "Pydantic schema validation",
      },
      {
        id: "prep-extraction",
        label: "Profile Extraction Agent",
        responsibility: "Extract skills, experience, and requirements",
        input: "Parsed resume + JD",
        output: "Candidate profile + job requirements",
        technology: "LangChain + LLM",
        failureMode: "Missing fields in sparse resumes",
        validationMethod: "Required field completeness check",
      },
      {
        id: "prep-gap",
        label: "Gap Analysis",
        responsibility: "Identify skill and experience gaps",
        input: "Profile + requirements",
        output: "Gap report",
        technology: "LangGraph node",
        failureMode: "Over-reporting minor gaps",
        validationMethod: "Threshold filtering",
      },
      {
        id: "prep-script",
        label: "Interview Script Builder",
        responsibility: "Generate targeted interview questions",
        input: "Gap report",
        output: "Question set",
        technology: "LangGraph node + LLM",
        failureMode: "Generic questions for specific roles",
        validationMethod: "Role-specific prompt tuning",
      },
      {
        id: "prep-evaluator",
        label: "Evaluator Agent",
        responsibility: "Score and assess candidate answers",
        input: "Answers + question context",
        output: "Per-answer scores",
        technology: "LangChain agent",
        failureMode: "Inconsistent scoring",
        validationMethod: "Structured output schema",
      },
      {
        id: "prep-coach",
        label: "Coach Agent",
        responsibility: "Generate improvement feedback",
        input: "Scores + answers",
        output: "Coaching recommendations",
        technology: "LangChain agent",
        failureMode: "Generic advice",
        validationMethod: "Evidence-linked suggestions",
      },
      {
        id: "prep-report",
        label: "Final Report",
        responsibility: "Compile structured coaching report",
        input: "All agent outputs",
        output: "PDF coaching report",
        technology: "Pydantic + PDF generation",
        failureMode: "Missing data sections",
        validationMethod: "Completeness assertion",
      },
    ],
  },
  {
    id: "medassist-mas",
    title: "MedAssist MAS",
    summary:
      "Safety-oriented multi-agent educational triage assistant with structured outputs and deterministic red-flag checks.",
    description:
      "A multi-agent healthcare triage demonstration using symptom analysis, pharmacy guidance, final consultation synthesis, structured JSON outputs, and conservative red-flag detection.",
    bestAngle: "Safety-aware agents and structured generation",
    disclaimer:
      "Educational decision-support demo only. Not a diagnostic or medical-care system.",
    featured: true,
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    githubUrl: "https://github.com/PRONGS-CHIRAG/MedAssist-MAS",
    tags: ["AutoGen", "Gradio", "Pydantic", "Healthcare AI", "Multi-Agent", "Safety"],
    category: "Agentic AI & RAG",
    architectureNodes: [
      {
        id: "med-input",
        label: "User Symptoms",
        responsibility: "Collect and validate symptom input",
        input: "Free-text symptoms",
        output: "Sanitised symptom string",
        technology: "Gradio interface",
        failureMode: "Ambiguous or incomplete input",
        validationMethod: "Input length and format check",
      },
      {
        id: "med-redflag",
        label: "Red-Flag Pre-Check",
        responsibility: "Deterministic emergency detection",
        input: "Symptom string",
        output: "Emergency flag or continue signal",
        technology: "Rule-based keyword matching",
        failureMode: "Novel emergency phrasing",
        validationMethod: "Conservative keyword list coverage",
      },
      {
        id: "med-diagnosis",
        label: "Diagnosis Agent",
        responsibility: "Educational symptom analysis",
        input: "Symptoms",
        output: "Educational differential",
        technology: "AutoGen agent",
        failureMode: "Overconfident language",
        validationMethod: "Non-diagnostic language prompt constraints",
      },
      {
        id: "med-pharmacy",
        label: "Pharmacy Agent",
        responsibility: "Self-care and OTC guidance",
        input: "Symptom + educational differential",
        output: "Self-care suggestions",
        technology: "AutoGen agent",
        failureMode: "Contraindication omissions",
        validationMethod: "Conservative output prompting",
      },
      {
        id: "med-consultation",
        label: "Consultation Agent",
        responsibility: "Synthesise final educational response",
        input: "All agent outputs",
        output: "Structured JSON response",
        technology: "AutoGen group chat manager",
        failureMode: "Conflicting agent outputs",
        validationMethod: "Pydantic output schema",
      },
    ],
  },
  {
    id: "speech-analyzer",
    title: "Speech Analyzer AI",
    summary:
      "AI meeting assistant that transcribes spoken content, normalises domain terminology, and creates structured minutes and action items.",
    description:
      "Processes audio with Whisper for transcription, applies domain terminology normalisation, and generates structured meeting minutes with action items via IBM watsonx and LangChain.",
    bestAngle: "Speech AI, domain adaptation, and workflow automation",
    featured: true,
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    githubUrl: "https://github.com/PRONGS-CHIRAG/Speech_Analyzer_AI",
    tags: ["Whisper", "Speech AI", "LangChain", "IBM watsonx", "Meeting Automation"],
    category: "Generative & Multimodal AI",
    architectureNodes: [
      {
        id: "speech-input",
        label: "Audio Input",
        responsibility: "Accept audio file or stream",
        input: "Audio file",
        output: "Raw audio",
        technology: "Gradio file upload",
        failureMode: "Unsupported audio format",
        validationMethod: "Format validation",
      },
      {
        id: "speech-transcription",
        label: "Whisper Transcription",
        responsibility: "Convert speech to text",
        input: "Raw audio",
        output: "Raw transcript",
        technology: "OpenAI Whisper",
        failureMode: "Background noise, accents",
        validationMethod: "Confidence score filtering",
      },
      {
        id: "speech-normalisation",
        label: "Terminology Normalisation",
        responsibility: "Correct domain-specific terms",
        input: "Raw transcript",
        output: "Normalised transcript",
        technology: "LangChain + IBM watsonx",
        failureMode: "Unknown acronyms",
        validationMethod: "Domain glossary coverage",
      },
      {
        id: "speech-structuring",
        label: "Minutes Generator",
        responsibility: "Extract structured minutes and actions",
        input: "Normalised transcript",
        output: "Structured minutes JSON",
        technology: "LangChain chain + LLM",
        failureMode: "Missing action items",
        validationMethod: "Required fields check",
      },
    ],
  },
  {
    id: "nourishbot",
    title: "AI NourishBot",
    summary:
      "Multimodal nutrition assistant that interprets food images and generates ingredient, nutritional, and recipe insights.",
    description:
      "Uses vision models to interpret food images and coordinates specialist agents via CrewAI to generate ingredient lists, nutritional analysis, dietary handling, and recipe suggestions.",
    bestAngle: "Multimodal AI and coordinated specialist agents",
    featured: true,
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    githubUrl: "https://github.com/PRONGS-CHIRAG/NourishBot---AI-Nutritionist",
    tags: ["Multimodal AI", "Vision", "CrewAI", "WatsonX", "Nutrition AI"],
    category: "Generative & Multimodal AI",
    architectureNodes: [
      {
        id: "nourish-input",
        label: "Food Image Input",
        responsibility: "Accept image upload",
        input: "Food photo",
        output: "Image data",
        technology: "Gradio image component",
        failureMode: "Non-food images",
        validationMethod: "Content type check",
      },
      {
        id: "nourish-vision",
        label: "Vision Interpretation",
        responsibility: "Identify food items in image",
        input: "Image data",
        output: "Food item list",
        technology: "WatsonX vision model",
        failureMode: "Mixed dish ambiguity",
        validationMethod: "Confidence threshold",
      },
      {
        id: "nourish-agents",
        label: "CrewAI Specialist Agents",
        responsibility: "Parallel nutritional analysis",
        input: "Food item list",
        output: "Nutritional breakdown + recipe suggestions",
        technology: "CrewAI multi-agent",
        failureMode: "Conflicting nutritional data",
        validationMethod: "Source cross-referencing",
      },
    ],
  },
  {
    id: "vidintel",
    title: "Vidintel",
    summary:
      "YouTube intelligence application for transcript extraction, summarisation, and grounded video question answering.",
    description:
      "Extracts YouTube transcripts (manual-priority), chunks and embeds with IBM Granite and WatsonX, indexes in FAISS, and enables summarisation and retrieval-based Q&A via Gradio.",
    bestAngle: "Video intelligence and retrieval pipelines",
    featured: true,
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    githubUrl: "https://github.com/PRONGS-CHIRAG/Vidintel",
    tags: ["YouTube", "FAISS", "WatsonX", "RAG", "Summarisation"],
    category: "Generative & Multimodal AI",
    architectureNodes: [
      {
        id: "vid-input",
        label: "YouTube URL",
        responsibility: "Accept and validate YouTube link",
        input: "YouTube URL",
        output: "Video ID",
        technology: "Gradio + youtube-transcript-api",
        failureMode: "Private or region-blocked videos",
        validationMethod: "URL format + availability check",
      },
      {
        id: "vid-transcript",
        label: "Transcript Extraction",
        responsibility: "Fetch manual or auto transcript",
        input: "Video ID",
        output: "Raw transcript text",
        technology: "youtube-transcript-api (manual priority)",
        failureMode: "No transcript available",
        validationMethod: "Fallback to auto-generated",
      },
      {
        id: "vid-chunking",
        label: "Chunking",
        responsibility: "Split transcript into segments",
        input: "Raw transcript",
        output: "Text chunks",
        technology: "RecursiveCharacterTextSplitter",
        failureMode: "Semantic unit fragmentation",
        validationMethod: "Chunk size tuning",
      },
      {
        id: "vid-embedding",
        label: "Embedding",
        responsibility: "Generate vector embeddings",
        input: "Text chunks",
        output: "Embedded vectors",
        technology: "IBM Granite / WatsonX embeddings",
        failureMode: "Embedding API latency",
        validationMethod: "Batch processing",
      },
      {
        id: "vid-faiss",
        label: "FAISS Index",
        responsibility: "Store and index vectors",
        input: "Embedded vectors",
        output: "Searchable index",
        technology: "FAISS",
        failureMode: "Index staleness on re-upload",
        validationMethod: "Index rebuild on new video",
      },
      {
        id: "vid-retrieval",
        label: "Similarity Retrieval",
        responsibility: "Find relevant segments for query",
        input: "User query",
        output: "Top-k chunks",
        technology: "FAISS similarity search",
        failureMode: "Low similarity scores for vague queries",
        validationMethod: "Minimum similarity threshold",
      },
      {
        id: "vid-generation",
        label: "Summary / Q&A Generation",
        responsibility: "Generate grounded response",
        input: "Top-k chunks + query",
        output: "Summary or answer",
        technology: "WatsonX LLM",
        failureMode: "Hallucination beyond transcript",
        validationMethod: "Grounding constraint in prompt",
      },
    ],
  },
  {
    id: "job-applying-buddy",
    title: "Job Applying Buddy",
    summary:
      "CrewAI-based workflow that generates tailored job-application materials from a vacancy, résumé, GitHub profile, and personal summary.",
    description:
      "Coordinates six specialist agents (researcher, profiler, strategist, interview preparer, translator, cover letter writer) to produce a tailored resume, interview prep package, cover letter, and PDF exports.",
    bestAngle: "Document automation and coordinated role-based agents",
    featured: true,
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    githubUrl: "https://github.com/PRONGS-CHIRAG/Job_Application_MAS",
    tags: ["CrewAI", "Gradio", "Resume AI", "Cover Letter AI", "PDF Generation"],
    category: "Agentic AI & RAG",
    architectureNodes: [
      {
        id: "job-input",
        label: "Input Collection",
        responsibility: "Gather job vacancy, resume, GitHub, summary",
        input: "Job URL, PDF resume, GitHub URL, personal summary",
        output: "Structured input bundle",
        technology: "Gradio multi-input",
        failureMode: "Missing required inputs",
        validationMethod: "Required field check",
      },
      {
        id: "job-researcher",
        label: "Tech Job Researcher",
        responsibility: "Research role and company",
        input: "Job URL",
        output: "Role and company insights",
        technology: "CrewAI agent + web tools",
        failureMode: "Private job posting",
        validationMethod: "Fallback to provided text",
      },
      {
        id: "job-profiler",
        label: "Personal Profiler",
        responsibility: "Extract candidate strengths",
        input: "Resume + GitHub + summary",
        output: "Candidate profile",
        technology: "CrewAI agent",
        failureMode: "Sparse GitHub activity",
        validationMethod: "Minimum profile fields",
      },
      {
        id: "job-strategist",
        label: "Resume Strategist",
        responsibility: "Tailor resume to vacancy",
        input: "Profile + role insights",
        output: "Tailored resume",
        technology: "CrewAI agent",
        failureMode: "Over-tailoring with inaccuracies",
        validationMethod: "Original fact grounding",
      },
      {
        id: "job-outputs",
        label: "Output Generation",
        responsibility: "Generate cover letter + PDF exports",
        input: "All agent outputs",
        output: "PDF resume + cover letter + interview prep",
        technology: "CrewAI + PDF generation",
        failureMode: "Formatting failures in PDF",
        validationMethod: "Template-based output",
      },
    ],
  },
  {
    id: "chaka",
    title: "Chaka",
    summary:
      "AI-assisted restoration decision-support prototype that ranks candidate land-restoration sites in Ethiopia and explains its recommendations with evidence-grounded agent reasoning.",
    description:
      "Built for the AI4Good Challenge hackathon, Chaka helps NGOs, government teams, and impact investors compare restoration areas using environmental indicators (satellite, soil, terrain, rainfall), livelihood context, and risk signals. A geospatial feature-extraction pipeline feeds a deterministic multi-factor scoring layer, which agentic components use to classify interventions, retrieve similar past cases, and generate explainable recommendations and project briefs via an evidence critic agent and chatbot. Built within a three-person team; this project's contribution was the reasoning layer, agent orchestration, recommendation logic, evidence checks, and brief generation.",
    bestAngle:
      "Evidence-grounded agent reasoning: deterministic geospatial scoring feeding explanation, risk-detection, and brief-generation agents that don't invent facts",
    featured: true,
    visibility: "public",
    verificationStatus: "verified-public",
    sourceType: "github",
    githubUrl: "https://github.com/PRONGS-CHIRAG/chaka2",
    tags: ["Multi-Agent", "RAG", "Explainable AI", "Geospatial AI", "Decision Support", "Next.js", "TypeScript"],
    category: "Agentic AI & RAG",
    architectureNodes: [
      {
        id: "chaka-ingestion",
        label: "Geospatial Data Ingestion",
        responsibility: "Extract satellite, soil, terrain, and population signals per site",
        input: "Satellite/geospatial sources (Sentinel-2, SRTM, SoilGrids, CHIRPS, WorldPop, GFW)",
        output: "Site feature table",
        technology: "Python/Node extraction scripts + feature extraction engine",
        failureMode: "Missing or stale source data",
        validationMethod: "Feature artifact schema validation",
      },
      {
        id: "chaka-candidates",
        label: "Candidate Site Generation",
        responsibility: "Build AOI boundaries and candidate restoration sites",
        input: "Admin boundaries + feature table",
        output: "Candidate site GeoJSON with canonical site IDs",
        technology: "AOI boundary builder + candidate site generator scripts",
        failureMode: "Duplicate or invalid site IDs",
        validationMethod: "Candidate site validation script",
      },
      {
        id: "chaka-scoring",
        label: "Multi-Factor Scoring",
        responsibility: "Score sites on biodiversity, carbon, water/soil, livelihood, and feasibility",
        input: "Candidate site features",
        output: "Component scores + final priority score",
        technology: "Deterministic scoring engine (TypeScript)",
        failureMode: "Overweighting a single indicator",
        validationMethod: "Configurable priority weights + rule-based ranker cross-check",
      },
      {
        id: "chaka-risk",
        label: "Risk & Safeguard Detection",
        responsibility: "Flag safeguard, protected-area overlap, and field-validation risks",
        input: "Site features + scores",
        output: "Risk level, risk flags, field-validation questions",
        technology: "Risk detection module (TypeScript)",
        failureMode: "Unflagged protected-area overlap",
        validationMethod: "WDPA overlap rule checks",
      },
      {
        id: "chaka-intervention",
        label: "Intervention Classification",
        responsibility: "Recommend an intervention type with confidence and rationale",
        input: "Scores + risk output",
        output: "Recommended intervention + confidence + rationale",
        technology: "Intervention classifier (TypeScript)",
        failureMode: "Low-confidence classification on sparse data",
        validationMethod: "Confidence threshold + rationale trace",
      },
      {
        id: "chaka-similarity",
        label: "Similar Cases Retrieval",
        responsibility: "Retrieve comparable historical restoration cases",
        input: "Site + recommended intervention",
        output: "Similar case set",
        technology: "Retrieval module over case library",
        failureMode: "No comparable cases in sparse regions",
        validationMethod: "Canonical case fallback matching",
      },
      {
        id: "chaka-explanation",
        label: "Explanation, Critic & Brief Agents",
        responsibility: "Generate grounded explanation, audit evidence, and compile a project brief",
        input: "Scores, risk output, intervention, similar cases",
        output: "Explanation, evidence critic notes, project brief",
        technology: "LLM agents (explanation, evidence critic, brief)",
        failureMode: "LLM invents unsupported geospatial facts",
        validationMethod: "Evidence critic agent + grounding constraint on numeric inputs",
      },
      {
        id: "chaka-delivery",
        label: "Frontend Delivery & Explainable Chat",
        responsibility: "Serve ranked map, recommendation detail, and Q&A chatbot",
        input: "Recommendation objects",
        output: "Interactive map, ranked list, project brief UI, chat answers",
        technology: "Next.js App Router + explainable chat API route",
        failureMode: "Chat answers drifting from underlying evidence",
        validationMethod: "Chat grounded to same evidence/critic outputs",
      },
    ],
  },
];

export const ALL_PROJECTS: ProjectItem[] = [
  ...FEATURED_PROJECTS,
  {
    id: "simple-agent",
    title: "Simple Agent",
    summary: "Foundational LLM agent implementation.",
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    tags: ["Agentic AI", "LLM"],
    category: "Agentic AI & RAG",
  },
  {
    id: "medical-chatbot",
    title: "Medical Chatbot",
    summary: "Conversational AI for medical Q&A.",
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    tags: ["Chatbot", "Healthcare AI"],
    category: "Agentic AI & RAG",
  },
  {
    id: "foodiebot",
    title: "FoodieBot",
    summary: "Conversational food recommendation assistant.",
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    tags: ["Chatbot", "Generative AI"],
    category: "Generative & Multimodal AI",
  },
  {
    id: "art-generation",
    title: "Artificial Art Generation",
    summary: "Generative art using diffusion and GAN models.",
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    tags: ["Generative AI", "GANs", "Computer Vision"],
    category: "Generative & Multimodal AI",
  },
  {
    id: "jazz-music-generation",
    title: "Jazz Music Generation",
    summary: "AI-generated jazz compositions.",
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    tags: ["Generative AI", "Music AI"],
    category: "Generative & Multimodal AI",
  },
  {
    id: "yolo-car-detection",
    title: "YOLO Car Detection",
    summary: "Real-time vehicle detection using YOLO.",
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    tags: ["Computer Vision", "YOLO", "Object Detection"],
    category: "Computer Vision",
  },
  {
    id: "covid-detection",
    title: "COVID-19 Detection using ResNets",
    summary: "Chest X-ray classification with ResNet architectures.",
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    tags: ["Computer Vision", "Deep Learning", "Healthcare AI"],
    category: "Computer Vision",
  },
  {
    id: "agriculture-drone",
    title: "Agriculture Drone",
    summary: "Autonomous drone system for precision agriculture.",
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    tags: ["IoT", "Computer Vision", "Embedded Systems"],
    category: "IoT & Embedded Systems",
  },
  {
    id: "stock-prediction",
    title: "Stock Prediction",
    summary: "Time-series ML models for stock price forecasting.",
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    tags: ["Applied ML", "Time Series", "Finance"],
    category: "Applied ML & Data",
  },
  {
    id: "evoting-dbms",
    title: "E-Voting DBMS",
    summary: "Secure electronic voting system with database backend.",
    visibility: "public",
    verificationStatus: "user-provided",
    sourceType: "github",
    tags: ["Software Engineering", "Database", "Security"],
    category: "Software Engineering",
  },
];

export const PROJECT_CATEGORIES = [
  "All",
  "Agentic AI & RAG",
  "Generative & Multimodal AI",
  "Computer Vision",
  "Applied ML & Data",
  "IoT & Embedded Systems",
  "Software Engineering",
];
